const events = [
  { id:'hackathon', number:'01', type:'BUILD', name:'Hackathon', short:'Build what matters.', description:'A high-energy innovation sprint for teams turning sharp ideas into useful, impactful products.', date:'12 OCT', time:'10:00 AM', team:'2-4', fee:'₹100', prize:'₹15,000', venue:'Innovation Lab', eligibility:'College students', rules:['Build in the given time window','Use original work and disclose APIs','Present a working demo to the jury'], image:'assets/hackathon.png' },
  { id:'ctf', number:'02', type:'SECURITY', name:'CTF', short:'Break the pattern.', description:'Find the flags through cryptography, web security, forensics and reverse engineering challenges.', date:'12 OCT', time:'11:00 AM', team:'1-3', fee:'₹100', prize:'₹10,000', venue:'Cyber Arena', eligibility:'Students and security enthusiasts', rules:['No attacking infrastructure outside the arena','Share flags only with your registered team','Highest score wins; time breaks ties'], image:'assets/ctf.png' },
  { id:'esports', number:'03', type:'PLAY', name:'E-Sports', short:'Play to win.', description:'Strategy, teamwork, reflexes and skill collide in the ultimate competitive gaming arena.', date:'12 OCT', time:'02:00 PM', team:'4-5', fee:'₹200', prize:'₹12,000', venue:'Main Auditorium', eligibility:'Registered college teams', rules:['Bring a valid college ID','Check in 30 minutes before the match','The referee decision is final'], image:'assets/esport.png' },
  { id:'treasure', number:'04', type:'ADVENTURE', name:'Treasure Hunt', short:'Follow the signal.', description:'Decode clues, overcome challenges and race across campus to uncover the final treasure.', date:'13 OCT', time:'10:00 AM', team:'3-5', fee:'₹100', prize:'₹8,000', venue:'GEHU Campus', eligibility:'All registered participants', rules:['Stay with your team throughout','Respect campus boundaries','Solve clues without damaging campus property'], image:'assets/treasure-hunt.png' },
  { id:'workshop', number:'05', type:'LEARN', name:'Workshop', short:'Leave with a new skill.', description:'Learn from practitioners, explore emerging technologies and turn theory into hands-on experience.', date:'13 OCT', time:'11:00 AM', team:'Open', fee:'Free', prize:'Certificate', venue:'Seminar Hall', eligibility:'Students and faculty', rules:['Seats are first come, first served','Carry a laptop for the practical session','Complete the feedback form for a certificate'], image:'assets/hackathon.png' }
]
const schedule = [['DAY 01','09:00','Doors open'],['DAY 01','10:00','Hackathon begins'],['DAY 01','11:00','CTF briefing'],['DAY 01','13:00','Lunch break'],['DAY 01','14:00','E-sports arena live'],['DAY 02','10:00','Treasure Hunt launch'],['DAY 02','11:00','Future skills workshop'],['DAY 02','18:00','HackSprint begins']]
const speakers = [['Dr. Meera Joshi','Innovation Director','GEHU','Leads student innovation programs and helps early ideas become useful products.','assets/merra.jpg'],['Arjun Mehta','Security Researcher','CyberLab India','A security educator who makes complex systems easier to question, test and protect.','assets/menspeaker.jpg'],['Riya Kapoor','Product Designer','Open Form Studio','Designs digital experiences where technology feels clear, generous and human.','assets/riya.jpg']]
const galleryGroups = [{id:'hackathon',number:'01',title:'Hackathon',note:'Build room',images:['20260418_095451.jpg','20260418_101029.jpg','20260418_110744.jpg']},{id:'ctf',number:'02',title:'CTF',note:'Cyber arena',images:['DSC_9762.JPG','DSC_9766.JPG','DSC_9778.JPG']},{id:'esport',number:'03',title:'E-sports',note:'Game on',images:['DSC08158.JPG','DSC08175.JPG','DSC_9816.JPG']},{id:'treasure-hunt',number:'04',title:'Treasure Hunt',note:'The hunt',images:['DSC_0090.JPG','DSC_0100.JPG','DSC_0111.JPG']}]

const eventGrid = document.querySelector('#eventGrid')
const scheduleList = document.querySelector('#scheduleList')
const speakerGrid = document.querySelector('#speakerGrid')
const galleryGroupsElement = document.querySelector('#galleryGroups')
const eventModal = document.querySelector('#eventModal')
const registrationModal = document.querySelector('#registrationModal')
const lightbox = document.querySelector('#lightbox')
const toast = document.querySelector('#toast')

function renderEvents(filter = 'ALL') {
  const visibleEvents = filter === 'ALL' ? events : events.filter((event) => event.type === filter)
  eventGrid.innerHTML = visibleEvents.map((event) => `<article class="event-card"><div class="event-image"><img src="${event.image}" alt="${event.name} poster"><span>${event.number} / ${event.type}</span></div><div class="event-card-body"><div class="event-title"><h3>${event.name}</h3><span>${event.short}</span></div><p>${event.description}</p><div class="event-facts"><span><b>DATE</b>${event.date}</span><span><b>TEAM</b>${event.team}</span><span><b>FEE</b>${event.fee}</span><span><b>PRIZE</b>${event.prize}</span></div><button class="details-link" data-event-id="${event.id}">View full details <span>↗</span></button></div></article>`).join('')
}
function renderSchedule() { scheduleList.innerHTML = schedule.map(([day,time,label]) => `<div class="schedule-item"><span class="schedule-day">${day}</span><strong>${time}</strong><span>${label}</span><span>◷</span></div>`).join('') }
function renderSpeakers() { speakerGrid.innerHTML = speakers.map(([name,role,organization,bio,image]) => `<article class="speaker-card"><img src="${image}" alt="${name}, ${role}"><div><p class="section-kicker">${role} / ${organization}</p><h3>${name}</h3><p>${bio}</p></div></article>`).join('') }
function renderGallery() { galleryGroupsElement.innerHTML = galleryGroups.map((group) => `<section class="gallery-group"><div class="gallery-group-heading"><p class="section-kicker">${group.number} / ${group.note}</p><h3>${group.title}</h3></div><div class="gallery-grid">${group.images.map((image,index) => `<figure data-image="assets/gallery/${group.id}/${image}" data-alt="${group.title} moment ${index + 1}"><img src="assets/gallery/${group.id}/${image}" alt="${group.title} moment ${index + 1}" loading="lazy"><figcaption><span>0${index + 1}</span> ${group.note}<b>↗</b></figcaption></figure>`).join('')}</div></section>`).join('') }
function showEvent(event) { document.querySelector('#eventType').textContent = `${event.number} / ${event.type}`; document.querySelector('#eventTitle').textContent = event.name; document.querySelector('#eventDescription').textContent = event.description; document.querySelector('#eventFacts').innerHTML = [['DATE',`${event.date} 2026`],['TIME',event.time],['VENUE',event.venue],['TEAM',`${event.team} people`],['FEE',event.fee],['ELIGIBILITY',event.eligibility]].map(([label,value]) => `<span><b>${label}</b>${value}</span>`).join(''); document.querySelector('#eventRules').innerHTML = event.rules.map((rule) => `<li>${rule}</li>`).join(''); eventModal.hidden = false }
function closeModals() { eventModal.hidden = true; registrationModal.hidden = true; lightbox.hidden = true }
function openRegistration() { closeModals(); document.querySelector('#registrationEvent').innerHTML = events.map((event) => `<option>${event.name}</option>`).join(''); registrationModal.hidden = false }
function updateCountdown() { const remaining = Math.max(0, new Date('2026-10-12T09:00:00+05:30').getTime() - Date.now()); const seconds = Math.floor(remaining / 1000); [['days',Math.floor(seconds / 86400)],['hours',Math.floor((seconds % 86400) / 3600)],['minutes',Math.floor((seconds % 3600) / 60)],['seconds',seconds % 60]].forEach(([id,value]) => { document.querySelector(`#${id}`).textContent = String(value).padStart(2,'0') }) }

renderEvents(); renderSchedule(); renderSpeakers(); renderGallery(); updateCountdown(); setInterval(updateCountdown,1000)
document.addEventListener('click', (event) => { const filter = event.target.closest('[data-filter]'); if (filter) { document.querySelectorAll('[data-filter]').forEach((button) => button.classList.toggle('active', button === filter)); renderEvents(filter.dataset.filter) } const details = event.target.closest('[data-event-id]'); if (details) showEvent(events.find((item) => item.id === details.dataset.eventId)); if (event.target.closest('[data-open-registration]')) openRegistration(); if (event.target.closest('[data-close-modal]')) closeModals(); const image = event.target.closest('[data-image]'); if (image) { document.querySelector('#lightboxImage').src = image.dataset.image; document.querySelector('#lightboxImage').alt = image.dataset.alt; lightbox.hidden = false } if (event.target === eventModal || event.target === registrationModal || event.target === lightbox) closeModals() })
document.querySelector('#registrationForm').addEventListener('submit', (event) => { event.preventDefault(); closeModals(); toast.hidden = false; setTimeout(() => { toast.hidden = true }, 4500) })
document.querySelector('.menu-button').addEventListener('click', (event) => { const nav = document.querySelector('.nav-links'); const open = nav.classList.toggle('open'); event.currentTarget.setAttribute('aria-expanded', open) })
document.querySelectorAll('.nav-links a').forEach((link) => link.addEventListener('click', () => document.querySelector('.nav-links').classList.remove('open')))
